/**
 * FFIEC BSA/AML Examination Manual — procedure matrix for audit readiness.
 * Maps examination areas to live platform evidence routes.
 */
export type ExaminationStatus = "not_started" | "in_progress" | "ready" | "gap" | "na";

export type EvidenceType = "live_api" | "page" | "doc" | "manual";

export interface ExaminationMatrixItem {
  id: string;
  domainId: string;
  domainName: string;
  procedure: string;
  ffiecRef: string;
  evidenceRoute?: string;
  evidenceType: EvidenceType;
  owner?: string;
  liveProbe?: "training" | "cases" | "filings" | "ctr" | "retention" | "validation" | "audit";
}

export const FFIEC_EXAMINATION_DOMAINS = [
  { id: "program", name: "BSA/AML Compliance Program" },
  { id: "internal-controls", name: "Internal Controls" },
  { id: "audit", name: "Independent Audit" },
  { id: "training", name: "Training" },
  { id: "cdd", name: "Customer Due Diligence" },
  { id: "sar", name: "Suspicious Activity Reporting" },
  { id: "ctr", name: "Currency Transaction Reporting" },
  { id: "sanctions", name: "OFAC / Sanctions" },
  { id: "tm", name: "Transaction Monitoring" },
  { id: "recordkeeping", name: "Recordkeeping" },
] as const;

export const FFIEC_EXAMINATION_MATRIX: ExaminationMatrixItem[] = [
  {
    id: "FFIEC-PROG-001",
    domainId: "program",
    domainName: "BSA/AML Compliance Program",
    procedure: "Board-approved AML/CFT programme documented and current",
    ffiecRef: "BSA/AML Manual · Scoping and Planning",
    evidenceRoute: "/governance",
    evidenceType: "page",
    owner: "MLRO",
  },
  {
    id: "FFIEC-PROG-002",
    domainId: "program",
    domainName: "BSA/AML Compliance Program",
    procedure: "MLRO appointed with independence and direct board access",
    ffiecRef: "BSA/AML Manual · MLRO",
    evidenceRoute: "/governance",
    evidenceType: "page",
    owner: "MLRO",
  },
  {
    id: "FFIEC-IC-001",
    domainId: "internal-controls",
    domainName: "Internal Controls",
    procedure: "Append-only audit trail for overrides, cases, filings, training",
    ffiecRef: "BSA/AML Manual · Internal Controls",
    evidenceRoute: "/audit",
    evidenceType: "live_api",
    owner: "Compliance",
    liveProbe: "audit",
  },
  {
    id: "FFIEC-IC-002",
    domainId: "internal-controls",
    domainName: "Internal Controls",
    procedure: "RBAC enforced server-side (MLRO / Reviewer / Analyst)",
    ffiecRef: "BSA/AML Manual · Internal Controls · IT",
    evidenceRoute: "/governance",
    evidenceType: "doc",
    owner: "MLRO",
  },
  {
    id: "FFIEC-AUD-001",
    domainId: "audit",
    domainName: "Independent Audit",
    procedure: "Independent model validation runs documented",
    ffiecRef: "BSA/AML Manual · Independent Testing",
    evidenceRoute: "/validation",
    evidenceType: "live_api",
    owner: "Compliance",
    liveProbe: "validation",
  },
  {
    id: "FFIEC-TRN-001",
    domainId: "training",
    domainName: "Training",
    procedure: "Role-based AML training assignments and completion register",
    ffiecRef: "BSA/AML Manual · Training",
    evidenceRoute: "/training",
    evidenceType: "live_api",
    owner: "MLRO",
    liveProbe: "training",
  },
  {
    id: "FFIEC-TRN-002",
    domainId: "training",
    domainName: "Training",
    procedure: "Training completion ≥ 90% (excluding waived)",
    ffiecRef: "BSA/AML Manual · Training",
    evidenceRoute: "/training",
    evidenceType: "live_api",
    owner: "MLRO",
    liveProbe: "training",
  },
  {
    id: "FFIEC-CDD-001",
    domainId: "cdd",
    domainName: "Customer Due Diligence",
    procedure: "CRAM risk rating with explainability and periodic review",
    ffiecRef: "BSA/AML Manual · CDD",
    evidenceRoute: "/cram",
    evidenceType: "page",
    owner: "Sayed",
  },
  {
    id: "FFIEC-CDD-002",
    domainId: "cdd",
    domainName: "Customer Due Diligence",
    procedure: "Screening disposition queue with SLA tracking",
    ffiecRef: "BSA/AML Manual · CDD · PEP",
    evidenceRoute: "/screening",
    evidenceType: "page",
    owner: "Sayed",
  },
  {
    id: "FFIEC-SAR-001",
    domainId: "sar",
    domainName: "Suspicious Activity Reporting",
    procedure: "Investigation cases with evidence chain (Mohsen pipeline)",
    ffiecRef: "BSA/AML Manual · SAR · Appendix L",
    evidenceRoute: "/investigation",
    evidenceType: "live_api",
    owner: "Mohsen",
    liveProbe: "cases",
  },
  {
    id: "FFIEC-SAR-002",
    domainId: "sar",
    domainName: "Suspicious Activity Reporting",
    procedure: "STR/SAR drafts with CBUAE · FFIEC App L compliance map",
    ffiecRef: "FFIEC Appendix L · SAR Quality",
    evidenceRoute: "/reporting",
    evidenceType: "live_api",
    owner: "Jana",
    liveProbe: "filings",
  },
  {
    id: "FFIEC-SAR-003",
    domainId: "sar",
    domainName: "Suspicious Activity Reporting",
    procedure: "Maker-checker and MLRO approval before FIU submission",
    ffiecRef: "CBUAE 3354/2022 · §5",
    evidenceRoute: "/reporting",
    evidenceType: "live_api",
    owner: "MLRO",
    liveProbe: "filings",
  },
  {
    id: "FFIEC-CTR-001",
    domainId: "ctr",
    domainName: "Currency Transaction Reporting",
    procedure: "CTR obligations queue · Form 104 draft · FinCEN BSA E-File submission",
    ffiecRef: "31 USC 5313 · 31 CFR 1010.311 · FinCEN Form 104",
    evidenceRoute: "/reporting?ctr=1",
    evidenceType: "live_api",
    owner: "MLRO",
    liveProbe: "ctr",
  },
  {
    id: "FFIEC-CTR-002",
    domainId: "ctr",
    domainName: "Currency Transaction Reporting",
    procedure: "Auto-register US cash ≥ $10,000 from TM with 15-day filing SLA",
    ffiecRef: "BSA/AML Manual · CTR · Recordkeeping",
    evidenceRoute: "/transaction-monitoring",
    evidenceType: "live_api",
    owner: "Mohsen",
    liveProbe: "ctr",
  },
  {
    id: "FFIEC-SAN-001",
    domainId: "sanctions",
    domainName: "OFAC / Sanctions",
    procedure: "Sanctions screening via Vital4 with disposition audit",
    ffiecRef: "BSA/AML Manual · OFAC",
    evidenceRoute: "/screening",
    evidenceType: "page",
    owner: "Sayed",
  },
  {
    id: "FFIEC-TM-001",
    domainId: "tm",
    domainName: "Transaction Monitoring",
    procedure: "TM alert ingestion and high/critical auto-case creation",
    ffiecRef: "BSA/AML Manual · TM",
    evidenceRoute: "/transaction-monitoring",
    evidenceType: "live_api",
    owner: "Mohsen",
    liveProbe: "cases",
  },
  {
    id: "FFIEC-TM-002",
    domainId: "tm",
    domainName: "Transaction Monitoring",
    procedure: "Typology library and corridor EWRA alignment",
    ffiecRef: "BSA/AML Manual · TM · Risk Assessment",
    evidenceRoute: "/transaction-monitoring",
    evidenceType: "page",
    owner: "Mohsen",
  },
  {
    id: "FFIEC-REC-001",
    domainId: "recordkeeping",
    domainName: "Recordkeeping",
    procedure: "5-year STR/SAR/CTR retention with disposition tracking",
    ffiecRef: "BSA/AML Manual · Recordkeeping · CBUAE §4.6",
    evidenceRoute: "/retention",
    evidenceType: "live_api",
    owner: "MLRO",
    liveProbe: "retention",
  },
  {
    id: "FFIEC-REC-002",
    domainId: "recordkeeping",
    domainName: "Recordkeeping",
    procedure: "Legal hold suspends archive eligibility (litigation / exam)",
    ffiecRef: "Mal Records Management Policy · Legal hold",
    evidenceRoute: "/retention",
    evidenceType: "live_api",
    owner: "MLRO",
    liveProbe: "retention",
  },
  {
    id: "FFIEC-REC-003",
    domainId: "recordkeeping",
    domainName: "Recordkeeping",
    procedure: "Governed evidence export with capability checks & manifest audit",
    ffiecRef: "Mal Evidence Export Policy · FFIEC examination",
    evidenceRoute: "/retention",
    evidenceType: "live_api",
    owner: "MLRO",
    liveProbe: "retention",
  },
  {
    id: "FFIEC-REC-004",
    domainId: "recordkeeping",
    domainName: "Recordkeeping",
    procedure: "Regulatory change monitor with impact assessment",
    ffiecRef: "BSA/AML Manual · Program · Regulatory",
    evidenceRoute: "/regulatory",
    evidenceType: "page",
    owner: "Sayed",
  },
];

export const MATRIX_BY_ID = Object.fromEntries(
  FFIEC_EXAMINATION_MATRIX.map((i) => [i.id, i]),
) as Record<string, ExaminationMatrixItem>;
