/**
 * Mal Bank — Transaction Monitoring System BRD, Section 12 "Scenario Inventory".
 * Source: TM System Implementation BRD v1.0 (2026-06-22), Compliance / MLRO.
 *
 * These 27 scenarios (SCN-001…SCN-027) are the CBUAE Mal Bank TM scenario set.
 * They are shown in the TM Rule Library (card #05) ONLY under the Mal Bank
 * perimeter, alongside the deployed Oscilar rule library.
 */

export interface BrdScenario {
  id: string;
  name: string;
  typology: string;
  riskCovered: string;
  segment: string;
  productChannel: string;
  logic: string;
  threshold: string;
  frequency: string;
  dataFields: string[];
  priority: string;
  expectedOutput: string;
  tuningNotes: string;
  uatRef: string;
}

export const BRD_SCENARIO_META = {
  documentId: "TM System Implementation BRD",
  version: "1.0",
  date: "2026-06-22",
  section: "Section 12 — Scenario Inventory",
  owner: "Compliance Department / MLRO",
  note: "CBUAE Mal Bank TM scenario inventory. Each scenario maps to a typology, threshold basis, data fields and a UAT reference; configuration and thresholds are approved through the BRD go-live gates (GATE-3 scenario/threshold, GATE-4 UAT).",
} as const;

export const BRD_SCENARIOS: BrdScenario[] = [
  { id: "SCN-001", name: "Structuring", typology: "ML", riskCovered: "Cash deposits below reporting/internal threshold within rolling period", segment: "Retail/SME/Corporate", productChannel: "Cash / Branch / ATM", logic: "Aggregate cash credits below threshold over 1/7/30 days", threshold: "Risk-based by customer type/rating", frequency: "Daily", dataFields: ["FIELD-CUST", "FIELD-ACCT", "FIELD-TXN"], priority: "Must", expectedOutput: "Alert with aggregate amount, count, period, branch/teller", tuningNotes: "Tune using historical cash patterns", uatRef: "UAT-SCN-001" },
  { id: "SCN-002", name: "Smurfing", typology: "ML", riskCovered: "Multiple small deposits by same or related parties", segment: "Retail/SME", productChannel: "Cash", logic: "Detect multiple depositors or repeated small values", threshold: "Risk-based count/value", frequency: "Daily", dataFields: ["FIELD-TXN", "FIELD-CUST", "FIELD-FRAUD"], priority: "Must", expectedOutput: "Alert with depositor/transaction clustering", tuningNotes: "Review false positives by cash-intensive segment", uatRef: "UAT-SCN-002" },
  { id: "SCN-003", name: "Rapid movement of funds", typology: "ML/TF", riskCovered: "Incoming funds followed by outgoing funds quickly", segment: "All", productChannel: "Transfers / Payments", logic: "Identify credit followed by debit within short window", threshold: "Percentage and time window threshold", frequency: "Daily/NRT", dataFields: ["FIELD-TXN", "FIELD-ACCT"], priority: "Must", expectedOutput: "Alert with source/destination and elapsed time", tuningNotes: "Tune by product settlement behaviour", uatRef: "UAT-SCN-003" },
  { id: "SCN-004", name: "High cash activity", typology: "ML", riskCovered: "Cash activity inconsistent with profile", segment: "Retail/SME/Corporate", productChannel: "Cash", logic: "Compare cash volume/value to expected activity and income/business profile", threshold: "Profile variance threshold", frequency: "Daily/Monthly", dataFields: ["FIELD-CUST", "FIELD-TXN"], priority: "Must", expectedOutput: "Alert with profile variance", tuningNotes: "Calibrate by segment", uatRef: "UAT-SCN-004" },
  { id: "SCN-005", name: "High-risk country activity", typology: "ML/TF/PF", riskCovered: "Transaction exposure to high-risk jurisdictions", segment: "All", productChannel: "International / Remittance", logic: "Trigger on originator, beneficiary, bank, country, corridor, or narrative", threshold: "Country risk list", frequency: "Daily/NRT", dataFields: ["FIELD-TXN", "FIELD-SCREEN"], priority: "Must", expectedOutput: "Alert with jurisdiction and list source", tuningNotes: "Update lists periodically", uatRef: "UAT-SCN-005" },
  { id: "SCN-006", name: "Sanctioned jurisdiction exposure", typology: "Sanctions/PF", riskCovered: "Direct/indirect exposure to sanctioned or embargoed jurisdictions", segment: "All", productChannel: "Payments / Transfers", logic: "Trigger on country, bank, counterparty, narrative, or screening status", threshold: "Zero / low tolerance", frequency: "NRT/Daily", dataFields: ["FIELD-SCREEN", "FIELD-TXN"], priority: "Must", expectedOutput: "Escalated sanctions/TFS alert", tuningNotes: "Coordinate with screening team", uatRef: "UAT-SCN-006" },
  { id: "SCN-007", name: "Multiple third-party transactions", typology: "ML", riskCovered: "Multiple unrelated third-party credits/debits", segment: "All", productChannel: "Transfers / Cash", logic: "Detect unrelated third-party activity inconsistent with profile", threshold: "Count/value threshold", frequency: "Daily", dataFields: ["FIELD-TXN", "FIELD-CUST"], priority: "Must", expectedOutput: "Alert with counterparties and relationship indicator", tuningNotes: "Enhance related-party data", uatRef: "UAT-SCN-007" },
  { id: "SCN-008", name: "Dormant reactivation", typology: "ML/Fraud", riskCovered: "Dormant account suddenly active", segment: "Retail/SME", productChannel: "Accounts / Transfers / Cash", logic: "Trigger on activity after dormancy with high value/velocity", threshold: "Dormancy period + activity threshold", frequency: "Daily", dataFields: ["FIELD-ACCT", "FIELD-TXN"], priority: "Must", expectedOutput: "Alert with dormancy period and activity", tuningNotes: "Exclude approved reactivation cases", uatRef: "UAT-SCN-008" },
  { id: "SCN-009", name: "New account high activity", typology: "ML/Fraud", riskCovered: "Newly opened account with high transaction volume", segment: "Retail/SME/Corporate", productChannel: "All", logic: "Compare early-life account activity to profile/segment", threshold: "First 30/60/90 day threshold", frequency: "Daily", dataFields: ["FIELD-CUST", "FIELD-ACCT", "FIELD-TXN"], priority: "Must", expectedOutput: "Alert with onboarding date and activity", tuningNotes: "Tune by acquisition campaign data", uatRef: "UAT-SCN-009" },
  { id: "SCN-010", name: "Round amount activity", typology: "ML", riskCovered: "Repeated round-value transactions", segment: "All", productChannel: "Cash / Transfers / Card", logic: "Detect repeated round values inconsistent with normal behaviour", threshold: "Count/value/time threshold", frequency: "Daily", dataFields: ["FIELD-TXN"], priority: "Should", expectedOutput: "Alert with repeated round amounts", tuningNotes: "Tune for loan installments and fees", uatRef: "UAT-SCN-010" },
  { id: "SCN-011", name: "Pass-through transactions", typology: "ML", riskCovered: "Funds pass through account with low balance retention", segment: "All", productChannel: "Transfers / Payments", logic: "Identify high credits and matching debits with minimal retained balance", threshold: "Flow-through ratio", frequency: "Daily/Monthly", dataFields: ["FIELD-TXN", "FIELD-ACCT"], priority: "Must", expectedOutput: "Alert with credit/debit sequence", tuningNotes: "Tune by merchant settlement accounts", uatRef: "UAT-SCN-011" },
  { id: "SCN-012", name: "Funnel account behaviour", typology: "ML/Fraud", riskCovered: "Many sources into one account then cash-out/outbound transfers", segment: "Retail/SME", productChannel: "Transfers / Cash", logic: "Detect many unrelated inbound sources and consolidated outflow", threshold: "Source count + outflow threshold", frequency: "Daily", dataFields: ["FIELD-TXN", "FIELD-FRAUD"], priority: "Must", expectedOutput: "Alert with inbound network and outflow", tuningNotes: "Use device/related-party data if available", uatRef: "UAT-SCN-012" },
  { id: "SCN-013", name: "Mule account behaviour", typology: "Fraud/ML", riskCovered: "Mule indicators with rapid cash-out and linked accounts", segment: "Retail/Digital", productChannel: "Digital / Instant / Cash", logic: "Detect new accounts, multiple third-party credits, rapid cash-out, device links", threshold: "Composite risk score", frequency: "NRT/Daily", dataFields: ["FIELD-FRAUD", "FIELD-TXN", "FIELD-CUST"], priority: "Must", expectedOutput: "Alert with mule indicators", tuningNotes: "Tune with confirmed fraud cases", uatRef: "UAT-SCN-013" },
  { id: "SCN-014", name: "Loan repayment by third party", typology: "ML", riskCovered: "Loan repayment by unrelated third party", segment: "Retail/SME/Corporate", productChannel: "Loans / Transfers / Cash", logic: "Detect repayment source not linked to borrower/approved related party", threshold: "Any/material threshold", frequency: "Daily", dataFields: ["FIELD-TXN", "FIELD-CUST", "FIELD-ACCT"], priority: "Must", expectedOutput: "Alert with payer relationship status", tuningNotes: "Maintain related-party data", uatRef: "UAT-SCN-014" },
  { id: "SCN-015", name: "Early settlement inconsistent with profile", typology: "ML", riskCovered: "Early settlement or overpayment inconsistent with income/source of funds", segment: "Retail/SME", productChannel: "Loans", logic: "Compare settlement amount/source to profile and expected activity", threshold: "Risk-based value threshold", frequency: "Daily", dataFields: ["FIELD-CUST", "FIELD-TXN"], priority: "Must", expectedOutput: "Alert with settlement source and variance", tuningNotes: "Tune by product campaigns", uatRef: "UAT-SCN-015" },
  { id: "SCN-016", name: "Merchant refund abuse", typology: "Fraud/ML", riskCovered: "Unusual refunds/chargebacks/circular activity", segment: "Merchant", productChannel: "Card / Merchant", logic: "Detect high refund rate, concentration, circularity, or card-linked abuse", threshold: "Rate/count/value threshold", frequency: "Daily", dataFields: ["FIELD-MERCH", "FIELD-TXN"], priority: "Should", expectedOutput: "Alert with refund pattern", tuningNotes: "Segment by MCC", uatRef: "UAT-SCN-016" },
  { id: "SCN-017", name: "Unusual card activity", typology: "Fraud/ML", riskCovered: "Card velocity, geolocation, CNP, and abnormal patterns", segment: "Retail/Merchant", productChannel: "Card", logic: "Detect abnormal spend, multiple failures/reversals, or atypical country/channel", threshold: "Velocity/risk threshold", frequency: "NRT/Daily", dataFields: ["FIELD-TXN", "FIELD-FRAUD"], priority: "Should", expectedOutput: "Alert with card token and pattern", tuningNotes: "Coordinate with fraud system", uatRef: "UAT-SCN-017" },
  { id: "SCN-018", name: "Digital channel abnormal activity", typology: "Fraud/ML", riskCovered: "Device/IP/session anomalies", segment: "Digital customers", productChannel: "Mobile / Online / API", logic: "Trigger on new device, high-risk IP, impossible travel, repeated attempts", threshold: "Composite risk score", frequency: "NRT/Daily", dataFields: ["FIELD-FRAUD", "FIELD-TXN"], priority: "Should", expectedOutput: "Alert with digital indicators", tuningNotes: "Availability depends on source metadata", uatRef: "UAT-SCN-018" },
  { id: "SCN-019", name: "Unusual remittance behaviour", typology: "ML/TF", riskCovered: "Frequent remittances to many beneficiaries or corridors", segment: "Retail/SME", productChannel: "Remittance", logic: "Detect high count/value/beneficiary/corridor variance", threshold: "Risk-based count/value", frequency: "Daily/Monthly", dataFields: ["FIELD-TXN", "FIELD-CUST"], priority: "Must", expectedOutput: "Alert with beneficiary/corridor profile", tuningNotes: "Tune by expatriate segment", uatRef: "UAT-SCN-019" },
  { id: "SCN-020", name: "Trade-related red flags", typology: "TBML/PF", riskCovered: "Trade activity inconsistent with licence, goods, or country risk", segment: "Corporate", productChannel: "Trade / Transfers", logic: "Detect import/export/dual-use/high-risk goods and inconsistent counterparties", threshold: "Risk list + variance threshold", frequency: "Daily", dataFields: ["FIELD-CUST", "FIELD-TXN"], priority: "Conditional", expectedOutput: "Alert with trade identifiers", tuningNotes: "Applicable where trade data is available", uatRef: "UAT-SCN-020" },
  { id: "SCN-021", name: "NGO/charity high-risk transactions", typology: "TF", riskCovered: "NPO/charity activity involving high-risk geography/cash/third parties", segment: "NPO/Charity customers", productChannel: "Transfers / Cash", logic: "Detect high-risk corridors, unusual donations, third-party patterns", threshold: "Risk-based threshold", frequency: "Daily", dataFields: ["FIELD-CUST", "FIELD-TXN"], priority: "Must if applicable", expectedOutput: "Alert with NPO risk factors", tuningNotes: "Require NPO classification", uatRef: "UAT-SCN-021" },
  { id: "SCN-022", name: "PEP unusual activity", typology: "ML/Corruption", riskCovered: "PEP activity inconsistent with profile or source of wealth", segment: "PEP customers", productChannel: "All", logic: "Enhanced PEP monitoring using profile variance and high-risk counterparties", threshold: "Lower thresholds", frequency: "Daily", dataFields: ["FIELD-CUST", "FIELD-TXN"], priority: "Must", expectedOutput: "Priority PEP alert", tuningNotes: "MLRO oversight", uatRef: "UAT-SCN-022" },
  { id: "SCN-023", name: "High-risk customer unusual activity", typology: "ML/TF/PF", riskCovered: "High-risk customer deviation from expected activity", segment: "High-risk customers", productChannel: "All", logic: "Lower threshold/higher priority for high-risk customers", threshold: "Risk-based", frequency: "Daily", dataFields: ["FIELD-CUST", "FIELD-TXN"], priority: "Must", expectedOutput: "High priority alert", tuningNotes: "Review risk rating feed", uatRef: "UAT-SCN-023" },
  { id: "SCN-024", name: "Virtual asset-related activity", typology: "VA/ML/TF/PF", riskCovered: "Payment token/VASP related risk indicators", segment: "Applicable customers", productChannel: "Token / Wallet / Transfers", logic: "Detect VASP identifiers, fiat-token conversion, high-risk VASP/country", threshold: "Risk-based / zero tolerance for prohibited", frequency: "Daily/NRT", dataFields: ["FIELD-VASP", "FIELD-TXN"], priority: "Conditional", expectedOutput: "Alert with VASP/token data", tuningNotes: "Applicable only if service provided", uatRef: "UAT-SCN-024" },
  { id: "SCN-025", name: "Proliferation financing indicators", typology: "PF", riskCovered: "Dual-use goods, sanctioned countries, front companies, unusual trade flows", segment: "Corporate/Trade", productChannel: "Transfers / Trade", logic: "Detect PF risk combinations across goods, country, counterparty, narrative", threshold: "Risk-based", frequency: "Daily", dataFields: ["FIELD-CUST", "FIELD-TXN", "FIELD-SCREEN"], priority: "Must if applicable", expectedOutput: "PF priority alert", tuningNotes: "Update PF red flags", uatRef: "UAT-SCN-025" },
  { id: "SCN-026", name: "Sanctions evasion indicators", typology: "Sanctions", riskCovered: "Obfuscation, intermediaries, unusual routing, narrative anomalies", segment: "All", productChannel: "Payments / Transfers", logic: "Detect evasion patterns with high-risk countries/counterparties/narratives", threshold: "Risk-based / zero tolerance", frequency: "NRT/Daily", dataFields: ["FIELD-SCREEN", "FIELD-TXN"], priority: "Must", expectedOutput: "Sanctions/TFS escalation", tuningNotes: "Integrate screening outputs", uatRef: "UAT-SCN-026" },
  { id: "SCN-027", name: "Fraud-linked transaction activity", typology: "Fraud/ML", riskCovered: "Confirmed fraud patterns linked to AML typologies", segment: "Retail/Digital/Merchant", productChannel: "All", logic: "Consume fraud flags and detect AML-relevant suspicious transaction behaviour", threshold: "Composite risk score", frequency: "Daily", dataFields: ["FIELD-FRAUD", "FIELD-TXN"], priority: "Should", expectedOutput: "Fraud/AML linked alert", tuningNotes: "Coordinate closure taxonomy", uatRef: "UAT-SCN-027" },
];
