/**
 * Payment purpose code disposition — TM & screening guidance.
 * Aligned to CRAM, MAL-CMP-AML-01 §8, Shari'ah, CBDDQ appetite, and Oscilar narrative screening.
 */

export type PurposeDisposition = "accept" | "accept_with_controls" | "eliminate";

export type PaymentPurposeCode = {
  id: string;
  label: string;
  originalLabel: string;
  disposition: PurposeDisposition;
  riskTier: "Low" | "Low–Medium" | "Medium" | "Medium–High" | "High" | "Prohibited";
  defaultEnabled: boolean;
  customerSegments: string[];
  channels: ("domestic_transfer" | "cross_border" | "card" | "wallet" | "api")[];
  controls: string[];
  policyRefs: string[];
  cramRefs: string[];
  tmScreeningNotes: string[];
  rationale: string;
};

export const PAYMENT_PURPOSE_GUIDANCE = {
  documentId: "MAL-TM-PPC-2026-01",
  version: "1.0.0",
  title: "Payment Purpose Code Disposition Guide",
  subtitle: "Transaction Monitoring & Screening — permitted, conditional, and prohibited payment narratives",
  documentType: "Operational guidance — TM / screening / payment rails",
  owner: "Head of Compliance / MLRO",
  preparedBy: "Mal FinCrime OS · Mohsen (TM investigator agent)",
  approvalForum: "MLRO · Compliance Committee · Payment Operations",
  confidentiality:
    "Confidential — internal use only. Not for external distribution without Compliance approval.",
  effectiveDate: "2026-06-29",
  modelVersion: "CRAM-CBUAE-2026-05-FREEZE-01",
  policyBasis: [
    "MAL-CMP-AML-01 §8 — Prohibited customer, activity, product and jurisdiction categories",
    "CRAM override hierarchy OVR-001 to OVR-020 — hard stops and risk floors (non-dilutable)",
    "CBUAE AML/CFT Rulebook — customer risk assessment, EDD, STR/SAR and TM requirements",
    "Mal Shari'ah compliance policy — riba, conventional insurance, prohibited sectors",
    "Wolfsberg CBDDQ correspondent-banking appetite — trade, MSB, PSP, charity restrictions",
    "Oscilar transaction monitoring — payment narrative screening and unusual purpose codes (CFG-12)",
  ],
  governingPrinciple:
    "Mal does not maintain a positive whitelist of every lawful payment globally. A purpose code is permitted only when the customer, beneficiary, corridor, and underlying activity pass all hard stops (OVR-001–OVR-007), Shari'ah constraints, and the controls listed for conditional codes. High inherent risk is acceptable with EDD — Prohibited is not.",
  dispositionDefinitions: [
    {
      tier: "Accept",
      code: "accept",
      summary: "Enable by default for eligible retail/SME segments with standard CDD and TM monitoring.",
      systemAction: "Purpose code selectable at onboarding and in payment flows. Standard Oscilar scenario pack.",
    },
    {
      tier: "Accept with controls",
      code: "accept_with_controls",
      summary: "Permitted only with enhanced checks, beneficiary validation, trade documentation, or Shari'ah-compliant routing.",
      systemAction: "Enable per segment/product. Pre-activation expected-activity match required. Enhanced TM scenarios and hold/step-up rules.",
    },
    {
      tier: "Eliminate",
      code: "eliminate",
      summary: "Do not offer as a selectable purpose. Block at product configuration and reject if submitted via API.",
      systemAction: "Hard-disabled in purpose-code catalogue. Oscilar rule: reject/hold + alert on attempted use.",
    },
  ],
  implementationRules: [
    "Configure purpose-code availability by CRA rating — High/Prohibited customers must not access codes beyond their approved expected-activity profile.",
    "Cross-border remittance corridors must validate purpose code against corridor EWRA typologies (e.g. PK service-export mismatch rules).",
    "Narrative screening (CFG-12) must flag purpose vs free-text mismatch, recycled invoices, and unusual code velocity.",
    "List screening hits on beneficiaries always mirror to Vital4 — never write CRAM fields directly from TM.",
    "High/Critical TM alerts on purpose-code abuse feed POST /api/v1/crr/events → reRate() → OVR-010 / OVR-020 as applicable.",
    "Split ambiguous codes in production: e.g. Insurance Services → Takaful premium (conditional accept) vs conventional insurance (eliminate).",
    "Loan interest payments must remain hard-eliminated — no manual override may re-enable riba-labelled purposes.",
  ],
  oscilarIntegration: {
    vendor: "Oscilar",
    screeningMirror: "Vital4 (sanctions / PEP / watchlist disposition authority)",
    configRefs: ["CFG-12 payment narrative screening", "CFG-29 transaction type / product / channel / purpose availability"],
    alertTiers: "Low → auto-close · Medium → analyst review · High/Critical → hold + CRAM feed + MLRO path",
  },
} as const;

export const PAYMENT_PURPOSE_CODES: PaymentPurposeCode[] = [
  {
    id: "PPC-001",
    label: "Air transport",
    originalLabel: "Air transport",
    disposition: "accept",
    riskTier: "Medium",
    defaultEnabled: true,
    customerSegments: ["Retail", "Affluent", "SME", "Corporate"],
    channels: ["domestic_transfer", "cross_border", "card"],
    controls: ["Verify travel merchant/MCC for card payments", "Cross-border ticket purchases — corridor screening"],
    policyRefs: ["MAL-CMP-AML-01 §8", "TM programme scope"],
    cramRefs: ["Product baseline — international transfers High by default"],
    tmScreeningNotes: ["Standard velocity and corridor rules"],
    rationale: "Legitimate travel and freight air services — core retail/corporate use case.",
  },
  {
    id: "PPC-002",
    label: "Allowance",
    originalLabel: "Allowance",
    disposition: "accept",
    riskTier: "Low–Medium",
    defaultEnabled: true,
    customerSegments: ["Retail", "Affluent"],
    channels: ["domestic_transfer", "cross_border"],
    controls: ["P2P allowance — beneficiary relationship plausibility"],
    policyRefs: ["MAL-CMP-AML-01"],
    cramRefs: ["NP segment — family support typology"],
    tmScreeningNotes: ["Monitor pass-through to unrelated beneficiaries"],
    rationale: "Personal/family allowance — standard retail remittance purpose.",
  },
  {
    id: "PPC-003",
    label: "Bonus",
    originalLabel: "Bonus",
    disposition: "accept",
    riskTier: "Low–Medium",
    defaultEnabled: true,
    customerSegments: ["Retail", "SME", "Corporate"],
    channels: ["domestic_transfer", "cross_border"],
    controls: ["Employer payroll linkage where B2B origin"],
    policyRefs: ["MAL-CMP-AML-01", "CBUAE payroll guidance"],
    cramRefs: ["Salary/payroll account — Low–Medium baseline"],
    tmScreeningNotes: ["Employer name match for corporate-origin bonuses"],
    rationale: "Employee compensation component — aligned to payroll use cases.",
  },
  {
    id: "PPC-004",
    label: "Charges for the use of intellectual property",
    originalLabel: "Charges for the use of intellectual property",
    disposition: "accept",
    riskTier: "Medium",
    defaultEnabled: true,
    customerSegments: ["SME", "Corporate"],
    channels: ["domestic_transfer", "cross_border", "api"],
    controls: ["License/royalty agreement reference for amounts > internal threshold"],
    policyRefs: ["MAL-CMP-AML-01", "TBML controls — intangible services"],
    cramRefs: ["Professional services — Medium inherent"],
    tmScreeningNotes: ["PK/IN corridor — service-export invoice validation where applicable"],
    rationale: "Legitimate licensing and royalty payments between verified parties.",
  },
  {
    id: "PPC-005",
    label: "Charitable contributions",
    originalLabel: "Charitable Contributions",
    disposition: "accept_with_controls",
    riskTier: "Medium–High",
    defaultEnabled: false,
    customerSegments: ["Retail", "Affluent", "SME"],
    channels: ["domestic_transfer", "cross_border"],
    controls: [
      "Beneficiary must be licensed, transparent NPO/charity — block opaque governance",
      "Enhanced screening for TF/sanctions nexus (FATF R.8)",
      "Senior approval for high-value or high-risk corridor donations",
    ],
    policyRefs: ["MAL-CMP-AML-01 §8", "FATF R.8 NPO abuse", "CBDDQ — opaque NPO prohibited"],
    cramRefs: ["OVR-002 if opaque charity", "Charity/NPO — conditional EDD"],
    tmScreeningNotes: ["Alert on charity + high-risk geography + velocity stacking"],
    rationale: "Permitted only to verified transparent charities — opaque NPOs are prohibited.",
  },
  {
    id: "PPC-006",
    label: "Commission",
    originalLabel: "Commission",
    disposition: "accept",
    riskTier: "Medium",
    defaultEnabled: true,
    customerSegments: ["Retail", "SME", "Corporate"],
    channels: ["domestic_transfer", "cross_border", "api"],
    controls: ["Commercial invoice or contract reference for B2B commissions"],
    policyRefs: ["MAL-CMP-AML-01"],
    cramRefs: ["SME operating account — Medium baseline"],
    tmScreeningNotes: ["TBML typology — commission without underlying trade"],
    rationale: "Standard commercial commission payments between verified counterparties.",
  },
  {
    id: "PPC-007",
    label: "Compensation",
    originalLabel: "Compensation",
    disposition: "accept",
    riskTier: "Low–Medium",
    defaultEnabled: true,
    customerSegments: ["Retail", "SME", "Corporate"],
    channels: ["domestic_transfer", "cross_border"],
    controls: ["SoF verification for non-payroll compensation"],
    policyRefs: ["MAL-CMP-AML-01"],
    cramRefs: ["NP employment parameter"],
    tmScreeningNotes: ["Standard payroll/compensation monitoring"],
    rationale: "General compensation payments — employment and contractual settlements.",
  },
  {
    id: "PPC-008",
    label: "Computer services",
    originalLabel: "Computer services",
    disposition: "accept",
    riskTier: "Medium",
    defaultEnabled: true,
    customerSegments: ["Retail", "SME", "Corporate"],
    channels: ["domestic_transfer", "cross_border", "card", "api"],
    controls: ["Service contract for recurring high-value IT payments"],
    policyRefs: ["MAL-CMP-AML-01"],
    cramRefs: ["ISIC J — Information and communication — Medium"],
    tmScreeningNotes: ["Digital goods / SaaS — merchant MCC validation on card"],
    rationale: "IT and computer services — ordinary professional/commercial purpose.",
  },
  {
    id: "PPC-009",
    label: "Construction",
    originalLabel: "Construction",
    disposition: "accept_with_controls",
    riskTier: "Medium–High",
    defaultEnabled: false,
    customerSegments: ["SME", "Corporate"],
    channels: ["domestic_transfer", "cross_border"],
    controls: [
      "Project/counterparty rationale for large or cross-border payments",
      "Subcontractor and procurement fraud screening",
      "License verification for construction entity customers",
    ],
    policyRefs: ["MAL-CMP-AML-01", "ISIC MH05 construction typology"],
    cramRefs: ["OVR-012 high-risk business within appetite", "ISIC 41–43 Medium inherent"],
    tmScreeningNotes: ["Large round amounts · invoice manipulation typologies"],
    rationale: "Allowed for licensed construction activity — elevated TBML and corruption typologies.",
  },
  {
    id: "PPC-010",
    label: "Educational support",
    originalLabel: "Educational support",
    disposition: "accept",
    riskTier: "Low–Medium",
    defaultEnabled: true,
    customerSegments: ["Retail", "Affluent"],
    channels: ["domestic_transfer", "cross_border", "card"],
    controls: ["Beneficiary institution verification for tuition payments"],
    policyRefs: ["MAL-CMP-AML-01"],
    cramRefs: ["NP retail — ordinary purpose"],
    tmScreeningNotes: ["Cross-border education — corridor plausibility"],
    rationale: "Tuition and educational support — core retail remittance purpose.",
  },
  {
    id: "PPC-011",
    label: "End of service or final settlement",
    originalLabel: "End of service or Final settlement",
    disposition: "accept",
    riskTier: "Low–Medium",
    defaultEnabled: true,
    customerSegments: ["Retail", "SME", "Corporate"],
    channels: ["domestic_transfer", "cross_border"],
    controls: ["Employer/gratuity documentation for large settlements"],
    policyRefs: ["UAE Labour Law gratuity", "MAL-CMP-AML-01"],
    cramRefs: ["Payroll/end-of-service — verified employer"],
    tmScreeningNotes: ["One-off large credit then rapid onward transfer — mule typology"],
    rationale: "UAE end-of-service gratuity and final settlement — primary payroll use case.",
  },
  {
    id: "PPC-012",
    label: "Equated monthly instalments (Islamic finance only)",
    originalLabel: "Equated Monthly Instalments",
    disposition: "eliminate",
    riskTier: "Prohibited",
    defaultEnabled: false,
    customerSegments: [],
    channels: [],
    controls: [
      "HARD BLOCK — conventional interest-based EMI = riba (Shari'ah prohibited)",
      "If reintroduced: restrict to Shari'ah-compliant Murabaha/Ijara instalments only with product validation",
    ],
    policyRefs: ["Mal Shari'ah policy — riba", "MAL-CMP-AML-01 §8"],
    cramRefs: ["OVR-002 — prohibited product/purpose under appetite"],
    tmScreeningNotes: ["Reject/hold + alert if submitted; log attempted riba-labelled payment"],
    rationale: "Eliminate unless product can prove Islamic finance structure. Conventional interest EMIs are riba.",
  },
  {
    id: "PPC-013",
    label: "Family support",
    originalLabel: "Family support",
    disposition: "accept",
    riskTier: "Low–Medium",
    defaultEnabled: true,
    customerSegments: ["Retail", "Affluent"],
    channels: ["domestic_transfer", "cross_border"],
    controls: ["Beneficiary relationship plausibility", "Corridor-typical amount bands"],
    policyRefs: ["MAL-CMP-AML-01", "Remittance corridor EWRA"],
    cramRefs: ["NP retail — core remittance purpose"],
    tmScreeningNotes: ["Core remittance scenario pack — South Asia/GCC corridors"],
    rationale: "Primary cross-border retail remittance purpose — enable by default.",
  },
  {
    id: "PPC-014",
    label: "Financial services",
    originalLabel: "Financial services",
    disposition: "accept_with_controls",
    riskTier: "High",
    defaultEnabled: false,
    customerSegments: ["SME", "Corporate"],
    channels: ["domestic_transfer", "cross_border", "api"],
    controls: [
      "Strict beneficiary screening — no unlicensed MSB, hawala, unlicensed VASP, shell entities",
      "Verify counterparty license where regulated activity",
      "Block nested/payable-through arrangements (CBDDQ)",
    ],
    policyRefs: ["MAL-CMP-AML-01 §8", "CBDDQ — PSP/MSB restrictions", "FinCEN MSB Rule"],
    cramRefs: ["OVR-002 / OVR-006 — unlicensed MSB prohibited", "OVR-014 FI exposure"],
    tmScreeningNotes: ["High alert tier — beneficiary entity type and license check"],
    rationale: "Broad category — permitted only to licensed, verified financial counterparties.",
  },
  {
    id: "PPC-015",
    label: "Goods bought — imports (CIF value)",
    originalLabel: "Goods bough - Imports in CIF value",
    disposition: "accept_with_controls",
    riskTier: "High",
    defaultEnabled: false,
    customerSegments: ["SME", "Corporate"],
    channels: ["domestic_transfer", "cross_border", "api"],
    controls: [
      "Trade documentation — invoice, customs, shipping docs",
      "TBML screening — over/under invoicing, phantom shipping",
      "Customer must not be general trading (CBDDQ prohibited) without licensed import activity",
      "Dual-use / sanctions goods screening",
    ],
    policyRefs: ["MAL-CMP-AML-01 §8 TBML", "CBDDQ — general trading prohibited", "FATF trade-based ML guidance"],
    cramRefs: ["OVR-012", "Trade finance — High baseline", "ISIC G wholesale — Medium–High"],
    tmScreeningNotes: ["PK/IN corridor — purpose vs NTN/filer mismatch rules", "Invoice hash reuse detection"],
    rationale: "Trade import payments — High inherent; permitted for verified licensed traders with EDD.",
  },
  {
    id: "PPC-016",
    label: "Goods sold — exports (FOB value)",
    originalLabel: "Goods sold - Exports in FOB value",
    disposition: "accept_with_controls",
    riskTier: "High",
    defaultEnabled: false,
    customerSegments: ["SME", "Corporate"],
    channels: ["domestic_transfer", "cross_border", "api"],
    controls: [
      "Export documentation and buyer verification",
      "TBML and over-invoicing controls",
      "Licensed exporter activity — not general trading shell",
    ],
    policyRefs: ["MAL-CMP-AML-01 §8 TBML", "CBDDQ"],
    cramRefs: ["OVR-012", "Trade finance — High baseline"],
    tmScreeningNotes: ["Service-export vs remittance purpose mismatch (PK corridor)"],
    rationale: "Trade export proceeds — High inherent; EDD and trade doc mandatory.",
  },
  {
    id: "PPC-017",
    label: "Income on investment funds / shares",
    originalLabel: "Income on Investments Funds Shares",
    disposition: "accept_with_controls",
    riskTier: "Medium–High",
    defaultEnabled: false,
    customerSegments: ["Affluent", "HNW", "SME"],
    channels: ["domestic_transfer", "cross_border"],
    controls: [
      "Shari'ah-compliant funds and approved exchanges only",
      "Block conventional/non-approved securities income",
      "SoW/SoF for investment income credits",
    ],
    policyRefs: ["Mal Shari'ah policy — non-Shari'ah securities prohibited", "MAL-CMP-AML-01"],
    cramRefs: ["OVR-002 if non-compliant securities"],
    tmScreeningNotes: ["Alert on investment income to/from high-risk VASP-like entities"],
    rationale: "Permitted only for Shari'ah-compliant investment distributions.",
  },
  {
    id: "PPC-018",
    label: "Information services",
    originalLabel: "Information Services",
    disposition: "accept",
    riskTier: "Medium",
    defaultEnabled: true,
    customerSegments: ["Retail", "SME", "Corporate"],
    channels: ["domestic_transfer", "cross_border", "card", "api"],
    controls: ["Contract reference for B2B information services"],
    policyRefs: ["MAL-CMP-AML-01"],
    cramRefs: ["ISIC J — Information — Medium"],
    tmScreeningNotes: ["Intangible service export typologies on cross-border"],
    rationale: "Data, research, and information services — standard commercial purpose.",
  },
  {
    id: "PPC-019",
    label: "Insurance services (Takaful only)",
    originalLabel: "Insurance Services",
    disposition: "eliminate",
    riskTier: "Prohibited",
    defaultEnabled: false,
    customerSegments: [],
    channels: [],
    controls: [
      "HARD BLOCK — conventional insurance prohibited (Shari'ah)",
      "Production split required: enable 'Takaful premium' as separate Shari'ah-compliant code if product supports",
    ],
    policyRefs: ["Mal Shari'ah policy — conventional insurance prohibited", "MAL-CMP-AML-01 §8"],
    cramRefs: ["OVR-002"],
    tmScreeningNotes: ["Reject conventional insurance premium narratives"],
    rationale: "Conventional insurance is Shari'ah-prohibited. Eliminate unless retagged to Takaful-only variant.",
  },
  {
    id: "PPC-020",
    label: "IPO subscriptions (Shari'ah-compliant only)",
    originalLabel: "IPO subscriptions",
    disposition: "accept_with_controls",
    riskTier: "Medium–High",
    defaultEnabled: false,
    customerSegments: ["Affluent", "HNW", "SME"],
    channels: ["domestic_transfer", "cross_border"],
    controls: [
      "Shari'ah board / approved exchange compliance check",
      "Block non-compliant or speculative prohibited offerings",
    ],
    policyRefs: ["Mal Shari'ah policy", "MAL-CMP-AML-01", "CBUAE securities rules"],
    cramRefs: ["OVR-002 if non-compliant offering"],
    tmScreeningNotes: ["Large subscription + rapid withdrawal — mule typology"],
    rationale: "Permitted only for Shari'ah-compliant IPO subscriptions on approved markets.",
  },
  {
    id: "PPC-021",
    label: "Leave salary",
    originalLabel: "Leave Salary",
    disposition: "accept",
    riskTier: "Low–Medium",
    defaultEnabled: true,
    customerSegments: ["Retail", "SME", "Corporate"],
    channels: ["domestic_transfer", "cross_border"],
    controls: ["Employer payroll verification"],
    policyRefs: ["UAE Labour Law", "MAL-CMP-AML-01"],
    cramRefs: ["Salary/payroll account"],
    tmScreeningNotes: ["Payroll cycle consistency"],
    rationale: "Accrued leave salary payment — standard UAE payroll component.",
  },
  {
    id: "PPC-022",
    label: "Loan charges (non-riba only)",
    originalLabel: "Loan Charges",
    disposition: "eliminate",
    riskTier: "Prohibited",
    defaultEnabled: false,
    customerSegments: [],
    channels: [],
    controls: [
      "HARD BLOCK where charges include interest/riba",
      "If reintroduced: Shari'ah-compliant facility/profit charges only with product attestation",
    ],
    policyRefs: ["Mal Shari'ah policy — riba", "MAL-CMP-AML-01 §8"],
    cramRefs: ["OVR-002"],
    tmScreeningNotes: ["Reject interest-labelled loan charge payments"],
    rationale: "Eliminate unless provably non-riba Shari'ah-compliant facility charges.",
  },
  {
    id: "PPC-023",
    label: "Loan interest payments",
    originalLabel: "Loan interst payments",
    disposition: "eliminate",
    riskTier: "Prohibited",
    defaultEnabled: false,
    customerSegments: [],
    channels: [],
    controls: ["HARD BLOCK — non-configurable. No manual override may re-enable."],
    policyRefs: ["Mal Shari'ah policy — riba (explicit prohibition)", "MAL-CMP-AML-01 §8"],
    cramRefs: ["OVR-002 — locked hard stop"],
    tmScreeningNotes: ["Immediate reject/hold + Critical alert + Compliance case"],
    rationale: "Explicit riba — absolute prohibition for Mal Islamic digital bank. Never enable.",
  },
  {
    id: "PPC-024",
    label: "Mobile wallet card cash-in",
    originalLabel: "Mobile wallet card cash-in",
    disposition: "accept_with_controls",
    riskTier: "High",
    defaultEnabled: false,
    customerSegments: ["Retail", "Affluent", "SME"],
    channels: ["wallet", "card"],
    controls: [
      "Verified customer only — no anonymous stored value (OVR-007)",
      "Velocity limits and mule/scam typology monitoring",
      "Device binding and step-up authentication",
    ],
    policyRefs: ["MAL-CMP-AML-01", "Product baseline — wallet High"],
    cramRefs: ["OVR-007 anonymous product prohibited", "Wallet — High baseline"],
    tmScreeningNotes: ["Cash-equivalent exposure — enhanced scenario pack", "Structuring near limits"],
    rationale: "High cash-equivalent risk — permitted with wallet product controls only.",
  },
  {
    id: "PPC-025",
    label: "Mobile wallet card payments",
    originalLabel: "Mobile walet card payments",
    disposition: "accept_with_controls",
    riskTier: "High",
    defaultEnabled: false,
    customerSegments: ["Retail", "Affluent", "SME"],
    channels: ["wallet", "card"],
    controls: ["MCC and merchant country screening", "Third-party payment beneficiary validation", "Velocity controls"],
    policyRefs: ["MAL-CMP-AML-01", "Product baseline — wallet/card Medium–High"],
    cramRefs: ["OVR-012 product high-risk features"],
    tmScreeningNotes: ["Gambling/adult MCC block", "Cross-border wallet spend — corridor rules"],
    rationale: "Stored-value payments — enable with card/wallet product eligibility and TM pack.",
  },
  {
    id: "PPC-026",
    label: "Other modes of transport",
    originalLabel: "Other modes of transport",
    disposition: "accept",
    riskTier: "Medium",
    defaultEnabled: true,
    customerSegments: ["Retail", "SME", "Corporate"],
    channels: ["domestic_transfer", "cross_border", "card"],
    controls: ["Transport merchant/MCC validation on card"],
    policyRefs: ["MAL-CMP-AML-01"],
    cramRefs: ["Travel/transport — Medium"],
    tmScreeningNotes: ["Standard transport corridor rules"],
    rationale: "Road, rail, and other transport payments — legitimate travel/logistics purpose.",
  },
  {
    id: "PPC-027",
    label: "Overtime",
    originalLabel: "Overtime",
    disposition: "accept",
    riskTier: "Low–Medium",
    defaultEnabled: true,
    customerSegments: ["Retail", "SME", "Corporate"],
    channels: ["domestic_transfer", "cross_border"],
    controls: ["Employer payroll linkage"],
    policyRefs: ["MAL-CMP-AML-01", "UAE Labour Law"],
    cramRefs: ["Salary/payroll"],
    tmScreeningNotes: ["Payroll pattern consistency"],
    rationale: "Overtime compensation — payroll-aligned purpose.",
  },
  {
    id: "PPC-028",
    label: "Own account transfer",
    originalLabel: "Own account transfer",
    disposition: "accept",
    riskTier: "Low",
    defaultEnabled: true,
    customerSegments: ["Retail", "Affluent", "SME", "Corporate"],
    channels: ["domestic_transfer", "cross_border", "wallet"],
    controls: ["Beneficiary must be same customer verified account"],
    policyRefs: ["MAL-CMP-AML-01"],
    cramRefs: ["Basic account — own-account transfers reduce mule risk"],
    tmScreeningNotes: ["Lowest-risk purpose — still monitor pass-through chains"],
    rationale: "Core low-risk purpose — transfers between customer's own verified accounts.",
  },
  {
    id: "PPC-029",
    label: "Pension",
    originalLabel: "Pension",
    disposition: "accept",
    riskTier: "Low–Medium",
    defaultEnabled: true,
    customerSegments: ["Retail", "Affluent"],
    channels: ["domestic_transfer", "cross_border"],
    controls: ["Pension authority/employer verification for credits"],
    policyRefs: ["MAL-CMP-AML-01"],
    cramRefs: ["NP pensioner segment — Low"],
    tmScreeningNotes: ["Regular pension pattern — deviation alerts"],
    rationale: "Retirement pension receipts and payments — standard retail purpose.",
  },
  {
    id: "PPC-030",
    label: "Personal cultural, audio, visual and recreation",
    originalLabel: "Personal cultural audio visual and recreation",
    disposition: "accept_with_controls",
    riskTier: "Medium–High",
    defaultEnabled: false,
    customerSegments: ["Retail", "Affluent"],
    channels: ["domestic_transfer", "cross_border", "card"],
    controls: [
      "Block gambling, adult entertainment, prohibited media/content (Shari'ah + AML §8)",
      "MCC screening on card — no casino/gaming/adult MCCs",
    ],
    policyRefs: ["MAL-CMP-AML-01 §8 gambling/adult prohibited", "Mal Shari'ah policy"],
    cramRefs: ["OVR-002 — gambling/adult prohibited", "ISIC 9200 score 4"],
    tmScreeningNotes: ["MCC 7995/7801 etc. hard block on card rail"],
    rationale: "Permitted for halal cultural/recreation — block prohibited entertainment subcategories.",
  },
  {
    id: "PPC-031",
    label: "Personal investments (Shari'ah-compliant only)",
    originalLabel: "Personal investments",
    disposition: "accept_with_controls",
    riskTier: "Medium–High",
    defaultEnabled: false,
    customerSegments: ["Affluent", "HNW"],
    channels: ["domestic_transfer", "cross_border"],
    controls: [
      "Shari'ah-compliant instruments only",
      "SoW/SoF and senior approval for HNW-sized flows",
      "No crypto/VAS unless licensed and in programme (product prohibited by default)",
    ],
    policyRefs: ["Mal Shari'ah policy", "MAL-CMP-AML-01 §8", "Product baseline — crypto Prohibited"],
    cramRefs: ["OVR-002 / OVR-006", "Crypto exposure prohibited unless licensed"],
    tmScreeningNotes: ["Investment + high-risk beneficiary — EDD alert"],
    rationale: "Permitted for compliant personal investments — block conventional/non-compliant assets.",
  },
  {
    id: "PPC-032",
    label: "Process, repair and maintenance services",
    originalLabel: "Process repair and maintenance services",
    disposition: "accept",
    riskTier: "Medium",
    defaultEnabled: true,
    customerSegments: ["Retail", "SME", "Corporate"],
    channels: ["domestic_transfer", "cross_border", "card"],
    controls: ["Service invoice for B2B maintenance contracts"],
    policyRefs: ["MAL-CMP-AML-01"],
    cramRefs: ["ISIC C/G services — Medium"],
    tmScreeningNotes: ["Standard commercial services monitoring"],
    rationale: "Industrial/commercial repair and maintenance — ordinary services purpose.",
  },
  {
    id: "PPC-033",
    label: "Professional and management consulting services",
    originalLabel: "Professional and management consulting services",
    disposition: "accept",
    riskTier: "Medium",
    defaultEnabled: true,
    customerSegments: ["SME", "Corporate"],
    channels: ["domestic_transfer", "cross_border", "api"],
    controls: ["Consulting contract for recurring high-value fees"],
    policyRefs: ["MAL-CMP-AML-01"],
    cramRefs: ["ISIC M professional services — Medium"],
    tmScreeningNotes: ["Intangible service TBML — PK corridor invoice rules"],
    rationale: "Management and professional consulting — standard B2B purpose.",
  },
  {
    id: "PPC-034",
    label: "Profits or rent on real estate",
    originalLabel: "Profits or rent on real estate",
    disposition: "accept_with_controls",
    riskTier: "Medium–High",
    defaultEnabled: false,
    customerSegments: ["Retail", "Affluent", "SME", "Corporate"],
    channels: ["domestic_transfer", "cross_border"],
    controls: [
      "Property ownership/tenancy verification",
      "SoF for large property income credits",
      "Real estate sector EDD for corporate landlords",
    ],
    policyRefs: ["MAL-CMP-AML-01", "ISIC L real estate — Medium–High"],
    cramRefs: ["OVR-012 for high-value property nexus"],
    tmScreeningNotes: ["Property flip / rapid rent cycling typologies"],
    rationale: "Legitimate rental and property income — elevated real-estate ML typologies.",
  },
  {
    id: "PPC-035",
    label: "Rent payments",
    originalLabel: "Rent payments",
    disposition: "accept",
    riskTier: "Medium",
    defaultEnabled: true,
    customerSegments: ["Retail", "Affluent", "SME"],
    channels: ["domestic_transfer", "cross_border", "card"],
    controls: ["Tenancy reference for recurring rent beneficiaries"],
    policyRefs: ["MAL-CMP-AML-01"],
    cramRefs: ["NP/SME ordinary purpose"],
    tmScreeningNotes: ["Rent + unrelated beneficiary — plausibility check"],
    rationale: "Residential/commercial rent — core retail and SME purpose.",
  },
  {
    id: "PPC-036",
    label: "Salary (compensation of employees)",
    originalLabel: "Salary(compensation of employees)",
    disposition: "accept",
    riskTier: "Low–Medium",
    defaultEnabled: true,
    customerSegments: ["Retail", "SME", "Corporate"],
    channels: ["domestic_transfer", "cross_border", "wallet", "api"],
    controls: ["WPS/employer verification where UAE payroll", "Salary account product linkage"],
    policyRefs: ["MAL-CMP-AML-01", "CBUAE WPS", "Product baseline — salary account"],
    cramRefs: ["Salary/payroll account — Low–Medium", "Primary NP use case"],
    tmScreeningNotes: ["Default enabled — core scenario pack", "Employer change + velocity"],
    rationale: "Primary Mal use case — salary receipt and payroll disbursement.",
  },
  {
    id: "PPC-037",
    label: "Salary advance",
    originalLabel: "Salary advance",
    disposition: "accept_with_controls",
    riskTier: "Medium",
    defaultEnabled: false,
    customerSegments: ["Retail", "SME"],
    channels: ["domestic_transfer", "wallet"],
    controls: [
      "Employer-verified payroll advance only",
      "Not a substitute for unsecured lending without credit policy",
      "Recovery via payroll deduction evidence",
    ],
    policyRefs: ["MAL-CMP-AML-01", "Internal credit policy"],
    cramRefs: ["Product limits and employer linkage"],
    tmScreeningNotes: ["Advance + no payroll credit — fraud typology"],
    rationale: "Permitted when tied to verified employer salary advance programme.",
  },
  {
    id: "PPC-038",
    label: "Sea transport",
    originalLabel: "Sea transport",
    disposition: "accept",
    riskTier: "Medium",
    defaultEnabled: true,
    customerSegments: ["SME", "Corporate"],
    channels: ["domestic_transfer", "cross_border", "card"],
    controls: ["Shipping/freight documentation for large B2B payments"],
    policyRefs: ["MAL-CMP-AML-01", "TBML — shipping typologies"],
    cramRefs: ["Transport — Medium", "Trade corridor controls"],
    tmScreeningNotes: ["Shipping + high-risk corridor — EDD"],
    rationale: "Maritime freight and shipping payments — legitimate trade/logistics purpose.",
  },
  {
    id: "PPC-039",
    label: "Stored value card cash-in",
    originalLabel: "Stored value card cash-in",
    disposition: "accept_with_controls",
    riskTier: "High",
    defaultEnabled: false,
    customerSegments: ["Retail", "Affluent", "SME"],
    channels: ["wallet", "card"],
    controls: ["Verified customer — OVR-007 anonymous block", "Cash-equivalent limits", "Mule/scam monitoring"],
    policyRefs: ["MAL-CMP-AML-01", "Product baseline — wallet Prohibited if anonymous"],
    cramRefs: ["OVR-007", "Wallet — High baseline"],
    tmScreeningNotes: ["Structuring · rapid cash-in cash-out"],
    rationale: "High-risk stored-value loading — wallet product with controls only.",
  },
  {
    id: "PPC-040",
    label: "Stored value card payments",
    originalLabel: "Stored value card payments",
    disposition: "accept_with_controls",
    riskTier: "High",
    defaultEnabled: false,
    customerSegments: ["Retail", "Affluent", "SME"],
    channels: ["wallet", "card"],
    controls: ["MCC screening", "Third-party beneficiary limits", "Velocity and device binding"],
    policyRefs: ["MAL-CMP-AML-01", "Product baseline — wallet/card"],
    cramRefs: ["OVR-012"],
    tmScreeningNotes: ["High-risk MCC block list", "Wallet spend deviation"],
    rationale: "Stored-value spend — enable with wallet/card eligibility.",
  },
  {
    id: "PPC-041",
    label: "Telecommunication services",
    originalLabel: "Telecommunication services",
    disposition: "accept",
    riskTier: "Low–Medium",
    defaultEnabled: true,
    customerSegments: ["Retail", "Affluent", "SME", "Corporate"],
    channels: ["domestic_transfer", "cross_border", "card"],
    controls: ["Telco merchant/MCC validation"],
    policyRefs: ["MAL-CMP-AML-01"],
    cramRefs: ["Utility/telco — ordinary retail"],
    tmScreeningNotes: ["Standard bill payment scenario"],
    rationale: "Mobile, fixed-line, and data services — core utility-style purpose.",
  },
  {
    id: "PPC-042",
    label: "Tickets",
    originalLabel: "Tickets",
    disposition: "accept_with_controls",
    riskTier: "Medium–High",
    defaultEnabled: false,
    customerSegments: ["Retail", "Affluent", "SME"],
    channels: ["domestic_transfer", "cross_border", "card"],
    controls: [
      "Block gambling/lottery/adult event tickets",
      "Travel/event ticket merchant validation",
      "Air/sea transport tickets — prefer specific transport purpose codes where available",
    ],
    policyRefs: ["MAL-CMP-AML-01 §8 gambling prohibited", "Mal Shari'ah"],
    cramRefs: ["OVR-002 — gambling", "ISIC 9200 prohibited"],
    tmScreeningNotes: ["MCC 7995 gaming block", "Travel ticket corridor plausibility"],
    rationale: "Permitted for legitimate travel/events — block gambling and prohibited entertainment tickets.",
  },
  {
    id: "PPC-043",
    label: "Transfer of funds between persons — normal account",
    originalLabel: "Transfer of funds between persons normal account",
    disposition: "accept",
    riskTier: "Medium",
    defaultEnabled: true,
    customerSegments: ["Retail", "Affluent"],
    channels: ["domestic_transfer", "cross_border"],
    controls: ["P2P beneficiary screening", "Mule/scam typology monitoring", "New beneficiary velocity"],
    policyRefs: ["MAL-CMP-AML-01", "TM P2P scenario pack"],
    cramRefs: ["Domestic transfers — Medium–High inherent"],
    tmScreeningNotes: ["Core P2P rules — new beneficiary + limit increase stacking"],
    rationale: "Standard person-to-person transfer — enable with P2P TM controls.",
  },
  {
    id: "PPC-044",
    label: "Travel",
    originalLabel: "Travel",
    disposition: "accept",
    riskTier: "Medium",
    defaultEnabled: true,
    customerSegments: ["Retail", "Affluent", "SME"],
    channels: ["domestic_transfer", "cross_border", "card"],
    controls: ["Travel merchant/agency validation", "Corridor plausibility"],
    policyRefs: ["MAL-CMP-AML-01"],
    cramRefs: ["NP retail remittance — travel purpose"],
    tmScreeningNotes: ["Standard travel spend scenarios"],
    rationale: "Personal and business travel expenses — core retail purpose.",
  },
  {
    id: "PPC-045",
    label: "Utility bill payments",
    originalLabel: "Utility Bill payments",
    disposition: "accept",
    riskTier: "Low–Medium",
    defaultEnabled: true,
    customerSegments: ["Retail", "Affluent", "SME"],
    channels: ["domestic_transfer", "card", "wallet"],
    controls: ["Utility biller registry validation"],
    policyRefs: ["MAL-CMP-AML-01"],
    cramRefs: ["Basic account — utility bill pay reduces mule profile when consistent"],
    tmScreeningNotes: ["Bill pay scenario — low priority unless deviation"],
    rationale: "DEWA/SEWA/etisalat-style utility payments — primary retail bill-pay use case.",
  },
];

export function purposeDispositionLabel(d: PurposeDisposition): string {
  if (d === "accept") return "Accept";
  if (d === "accept_with_controls") return "Accept with controls";
  return "Eliminate";
}

export function purposeDispositionCounts() {
  const accept = PAYMENT_PURPOSE_CODES.filter((c) => c.disposition === "accept").length;
  const conditional = PAYMENT_PURPOSE_CODES.filter((c) => c.disposition === "accept_with_controls").length;
  const eliminate = PAYMENT_PURPOSE_CODES.filter((c) => c.disposition === "eliminate").length;
  return { accept, conditional, eliminate, total: PAYMENT_PURPOSE_CODES.length };
}

export const PAYMENT_PURPOSE_TABLE_OF_CONTENTS = [
  "Document control & metadata",
  "Executive summary",
  "Governing framework & policy basis",
  "Disposition methodology (Accept · Accept with controls · Eliminate)",
  "Summary statistics",
  "Section A — Eliminate (prohibited purpose codes)",
  "Section B — Accept with controls (conditional purpose codes)",
  "Section C — Accept (standard purpose codes)",
  "Oscilar TM & narrative screening integration",
  "Implementation rules & system configuration",
  "MLRO / Compliance sign-off",
] as const;
