/** Partnership registry — sourced exclusively from 01 Partnerships zip (Jun 2026). */

export const CATEGORIES = [
  { id: "Payout partners", color: "#8000ff", note: "Cross-border remittance & last-mile disbursement" },
  { id: "Banking partner", color: "#1e63e9", note: "FBO / USD banking rails" },
  { id: "Virtual accounts", color: "#0284c7", note: "Virtual account infrastructure (proposal stage)" },
  { id: "Card & settlement", color: "#0ea5e9", note: "Card issuing, processing & settlement" },
  { id: "KYC & identity", color: "#6366f1", note: "Identity verification — processor; Mal retains CDD accountability" },
  { id: "Risk platform", color: "#dc2626", note: "Fraud, device intelligence & risk workflows" },
  { id: "System integrator", color: "#7c3aed", note: "TM, screening, core banking, API & data integration vendors" },
  { id: "Lending", color: "#059669", note: "Earned-wage / lending programmes" },
];

const DOC = "01 Partnerships repository";

export const AGENTS_BASE = [
  {
    id: "swiftx", name: "SwiftX DLT Pay Ltd", category: "Payout partners",
    relationship: "Pakistan corridor cross-border payout — Platform Services (FINTRAC MSB)",
    jur: "Pakistan", juris: ["Pakistan", "Canada"], license: "FINTRAC MSB (SwiftX Canada); technology via SwiftX Meydan",
    tier: "Critical", live: true, relType: "Outsourcing",
    gates: { s24DD: true, amlContract: true, auditRights: true, dataProtection: true, ongoingMonitoring: true, terminationRights: true, approvedBy: "MLRO", reDDDue: "2028-05-01", blockingNote: null },
    contacts: [{ role: "Contract counterparty", name: "SwiftX DLT Pay Ltd", email: "—" }],
    agreement: {
      entity: "SwiftX DLT Pay Ltd (SwiftX Canada)", counterparty: "Mal Digital Ltd (ADGM, co. 25182)",
      signedFor: "Executed via DocuSign", effective: "1 May 2026", term: "2-year initial; auto-renewal 2-year periods",
      notice: "Per Agreement §19–21", commercial: "Schedule 1 — Pakistan corridor; API uptime 99.95%; PKR 98% disbursed ≤15 min; MMVC deferred first 6 months",
      governingLaw: "Per Platform Services Agreement", status: "Executed (signed PSA)", doc: "Platform Service Agreement — Execution Version (Signed.pdf)",
    },
    contractDisputes: [
      { id: "sx-d1", topic: "Monthly minimum volume commitment timing", malPosition: "Confirm MMVC threshold only at 6-month mark per Schedule 1", vendorPosition: "MMVC not applied first 6 months — threshold TBD at month 6", status: "Open", contractRef: "Schedule 1 — MMVC", source: DOC },
    ],
    scores: { reporting: 78, responsiveness: 72, training: 90, audit: 70, findings: 60, timeliness: 65, quality: 80, cooperation: 85, risk: 55 },
    history: [70, 72, 74, 76, 78],
  },
  {
    id: "thunes", name: "Thunes", category: "Payout partners",
    relationship: "Multi-corridor payout — commercial proposal only (no executed PSA in repository)",
    jur: "Global", juris: ["Global"], license: "Per Thunes corridor authorisations (proposal stage)",
    tier: "High", live: false, relType: "Outsourcing",
    gates: { s24DD: false, amlContract: false, auditRights: false, dataProtection: false, ongoingMonitoring: false, terminationRights: false, approvedBy: null, reDDDue: null, blockingNote: "No executed agreement in repository — Commercial Proposal only; not operational" },
    contacts: [{ role: "Commercial", name: "Not listed in repository", email: "—" }],
    agreement: {
      entity: "Thunes", counterparty: "Mal (entity not specified on proposal)", signedFor: "—",
      effective: "—", term: "—", notice: "—", commercial: "Commercial Proposal - Mal.ai.xlsx (internal projections also in repository)",
      governingLaw: "—", status: "Proposal — no executed contract", doc: "Commercial Proposal - Mal.ai.xlsx",
    },
    contractDisputes: [
      { id: "th-d1", topic: "No master services agreement", malPosition: "Require executed PSA with SLA, audit rights and corridor schedule before onboarding", vendorPosition: "Commercial proposal only — definitive agreement pending", status: "Unresolved", contractRef: "Commercial Proposal - Mal.ai.xlsx", source: DOC },
    ],
    scores: { reporting: 0, responsiveness: 0, training: 0, audit: 0, findings: 0, timeliness: 0, quality: 0, cooperation: 0, risk: 50 },
    history: [0, 0, 0, 0, 0],
  },
  {
    id: "zenus", name: "Zenus Bank International, Inc.", category: "Banking partner",
    relationship: "USD FBO master account, sub-accounts, ACH, settlement, Visa BIN programme",
    jur: "United States", juris: ["United States", "Puerto Rico"], license: "IFE-061 — OCIF Puerto Rico (Act 273/2012); not FDIC-insured",
    tier: "Critical", live: true, relType: "Outsourcing",
    gates: { s24DD: true, amlContract: true, auditRights: true, dataProtection: true, ongoingMonitoring: true, terminationRights: true, approvedBy: "MLRO", reDDDue: "2028-06-08", blockingNote: null },
    contacts: [{ role: "Head of Risk (signatory)", name: "Jorge M. Soltero", email: "—" }],
    kdp: [{ name: "Jorge M. Soltero", role: "Head of Risk — Zenus signatory" }],
    agreement: {
      entity: "Zenus Bank International, Inc.", counterparty: "Mal Money, Inc. (Program Manager)",
      signedFor: "Mal: Abdallah Abu Sheikh (Sole Director)", effective: "8 June 2026", term: "36-month initial; 1-year renewals",
      notice: "90 days non-renewal; settlement-failure cure 5 business days", commercial: "Cover sheet: onboarding $25,000; min FBO balance $50,000; monthly min fee ramp Month 4–6 $5k → Month 10+ $15k",
      governingLaw: "Puerto Rico", status: "Executed", doc: "Program Services Agreement — FBO Final 20260608.pdf",
    },
    contractDisputes: [
      { id: "z-d1", topic: "SAR/CTR filing institution (Path A vs B)", malPosition: "Document whether Mal or Zenus files SAR/CTR as BSA reporting institution", vendorPosition: "PSA executed; filing allocation not resolved in programme schedule", status: "Open", contractRef: "Program Services Agreement + Mal gap analysis", source: DOC },
      { id: "z-d2", topic: "Independent AML audit in Schedule 3.6(a)", malPosition: "Add explicit independent AML/BSA audit obligation cross-referenced in programme", vendorPosition: "Schedule references audit pillar but omits standalone audit clause", status: "Open", contractRef: "Mal Money - FBO Agreement Schedules - Mal Comments.docx", source: DOC },
      { id: "z-d3", topic: "MSB / regulatory perimeter", malPosition: "Align programme MSB determination with executed PSA status", vendorPosition: "Perimeter treated inconsistently between programme memo and PSA", status: "Open", contractRef: "Program Services Agreement", source: DOC },
    ],
    scores: { reporting: 88, responsiveness: 86, training: 82, audit: 74, findings: 76, timeliness: 84, quality: 84, cooperation: 86, risk: 80 },
    history: [86, 86, 85, 84, 82],
  },
  {
    id: "keel", name: "Keel", category: "Virtual accounts",
    relationship: "USD virtual account infrastructure — quote & CDD pack only",
    jur: "Global", juris: ["Global"], license: "Not specified in repository quote",
    tier: "High", live: false, relType: "Outsourcing",
    gates: { s24DD: false, amlContract: false, auditRights: false, dataProtection: false, ongoingMonitoring: false, terminationRights: false, approvedBy: null, reDDDue: null, blockingNote: "No executed agreement — Mal.AI quote v3 and CDD template only" },
    contacts: [{ role: "Commercial", name: "Not listed in repository", email: "—" }],
    agreement: {
      entity: "Keel", counterparty: "Mal (entity not on quote)", signedFor: "—", effective: "—", term: "—",
      notice: "—", commercial: "Mal.AI quote v3 290126 (2).pdf", governingLaw: "—", status: "Quote — no executed contract", doc: "Mal.AI quote v3 290126 (2).pdf",
    },
    contractDisputes: [
      { id: "ke-d1", topic: "No master agreement or SLA", malPosition: "Require executed virtual-account agreement with audit rights before use", vendorPosition: "Pricing quote and CDD questionnaire only", status: "Unresolved", contractRef: "Mal.AI quote v3 290126 (2).pdf", source: DOC },
    ],
    scores: { reporting: 0, responsiveness: 0, training: 0, audit: 0, findings: 0, timeliness: 0, quality: 0, cooperation: 0, risk: 50 },
    history: [0, 0, 0, 0, 0],
  },
  {
    id: "rain", name: "Signify Holdings, Inc. (Rain)", category: "Card & settlement",
    relationship: "Visa card issuing sponsorship, programme management & stablecoin settlement",
    jur: "United States", juris: ["United States"], license: "Card issuing programme — issuing depository not named in MSA draft",
    tier: "Critical", live: false, relType: "Outsourcing",
    gates: { s24DD: true, amlContract: false, auditRights: false, dataProtection: false, ongoingMonitoring: false, terminationRights: false, approvedBy: null, reDDDue: null, blockingNote: "MSA not executed — MLRO hold (Schedule 1 ToS controls; issuing bank unnamed)" },
    contacts: [{ role: "Signify contact", name: "Kay Galarza", email: "—" }, { role: "Mal program owner", name: "Loay Osama", email: "loay.malahmeh@mal.ai" }],
    kdp: [{ name: "Signify Holdings, Inc.", role: "Card issuing entity (brand: Rain)" }],
    agreement: {
      entity: "Signify Holdings, Inc. (brand: Rain)", counterparty: "Mal Money Inc. (Partner)",
      signedFor: "Mal: pending signature", effective: "On last signature (MSA draft in repository)", term: "5-year initial; auto-renew 1-year",
      notice: "90 days non-renewal", commercial: "Partner bears 100% program losses; reserve 4× largest daily settlement; USDC/USDG free, USDT 10 bps",
      governingLaw: "Schedule 1 Terms of Service control MSA (unilaterally amendable)", status: "Draft — MLRO review (Do Not Sign)", doc: "Card Issuing & Program Management Agreement (MSA draft)",
    },
    contractDisputes: [
      { id: "r-d1", topic: "Issuing depository bank unnamed", malPosition: "Name issuing bank and attach BSA/AML responsibility matrix before signature", vendorPosition: "Issuing institution not identified in MSA draft", status: "Open", contractRef: "MSA draft", source: DOC },
      { id: "r-d2", topic: "Schedule 1 ToS unilateral amendment", malPosition: "Carve AML, sanctions and consumer protection from unilateral ToS changes; require bilateral consent", vendorPosition: "Schedule 1 ToS incorporated and controls over MSA", status: "Open", contractRef: "MSA Schedule 1", source: DOC },
      { id: "r-d3", topic: "100% program loss allocation", malPosition: "Cap force-post/fraud liability; require commensurate real-time controls", vendorPosition: "Partner responsible for all provisional credits, chargebacks and fraud losses", status: "Open", contractRef: "MSA Schedule 2", source: DOC },
      { id: "r-d4", topic: "Co-Brand Agreement missing", malPosition: "Obtain referenced Co-Brand Agreement before execution", vendorPosition: "Co-Brand Agreement referenced but not attached to repository MSA", status: "Open", contractRef: "MSA Schedule 3", source: DOC },
    ],
    scores: { reporting: 70, responsiveness: 72, training: 70, audit: 68, findings: 42, timeliness: 72, quality: 66, cooperation: 70, risk: 52 },
    history: [80, 78, 74, 68, 60],
  },
  {
    id: "clowd9", name: "CLOWD9", category: "Card & settlement",
    relationship: "Card processor pricing — no executed processing agreement in repository",
    jur: "Global", juris: ["Global"], license: "Processor pricing proposal only",
    tier: "High", live: false, relType: "Outsourcing",
    gates: { s24DD: false, amlContract: false, auditRights: false, dataProtection: false, ongoingMonitoring: false, terminationRights: false, approvedBy: null, reDDDue: null, blockingNote: "Processor pricing PDF only — no master agreement" },
    contacts: [{ role: "Commercial", name: "Not listed in repository", email: "—" }],
    agreement: {
      entity: "CLOWD9", counterparty: "Mal Bank (per pricing deck title)", signedFor: "—", effective: "—", term: "—",
      notice: "—", commercial: "CLOWD9 _ Mal Bank Processor pricing 20_06.pdf", governingLaw: "—", status: "Pricing proposal — no executed contract", doc: "CLOWD9 _ Mal Bank Processor pricing 20_06.pdf",
    },
    contractDisputes: [
      { id: "c9-d1", topic: "No processing master agreement", malPosition: "Require executed card-processing MSA with SLA and audit rights", vendorPosition: "Pricing deck only in repository", status: "Unresolved", contractRef: "CLOWD9 _ Mal Bank Processor pricing 20_06.pdf", source: DOC },
    ],
    scores: { reporting: 0, responsiveness: 0, training: 0, audit: 0, findings: 0, timeliness: 0, quality: 0, cooperation: 0, risk: 50 },
    history: [0, 0, 0, 0, 0],
  },
  {
    id: "i2c", name: "i2c Inc.", category: "Card & settlement",
    relationship: "Debit card processing — financial proposal & projections only",
    jur: "United States", juris: ["United States", "Global"], license: "Card processor (proposal stage)",
    tier: "High", live: false, relType: "Outsourcing",
    gates: { s24DD: false, amlContract: false, auditRights: false, dataProtection: false, ongoingMonitoring: false, terminationRights: false, approvedBy: null, reDDDue: null, blockingNote: "Financial proposal and projections — no executed processing agreement" },
    contacts: [{ role: "Commercial", name: "Not listed in repository", email: "—" }],
    agreement: {
      entity: "i2c Inc.", counterparty: "Mal.ai (per proposal)", signedFor: "—", effective: "—", term: "—",
      notice: "—", commercial: "i2c Financial Proposal_Mal.ai_04202026.pdf", governingLaw: "—", status: "Proposal — no executed contract", doc: "i2c Financial Proposal_Mal.ai_04202026.pdf",
    },
    contractDisputes: [
      { id: "i2-d1", topic: "No processing agreement or SLA", malPosition: "Execute card-processing MSA before programme dependency", vendorPosition: "Financial proposal and confidential projections only", status: "Unresolved", contractRef: "i2c Financial Proposal_Mal.ai_04202026.pdf", source: DOC },
    ],
    scores: { reporting: 0, responsiveness: 0, training: 0, audit: 0, findings: 0, timeliness: 0, quality: 0, cooperation: 0, risk: 50 },
    history: [0, 0, 0, 0, 0],
  },
  {
    id: "shufti", name: "Shufti Pro Limited", category: "KYC & identity",
    relationship: "Document verification, OCR, face verification & liveness (processor — Mal retains CDD accountability)",
    jur: "Global", juris: ["Global"], license: "IDV processor — UK co. 11039567",
    tier: "High", live: true, relType: "System",
    gates: { assuranceAssessed: false, appropriatenessAssessed: false, dataLocalisation: true, authControlsChecked: true, approvedBy: "Compliance", reDDDue: "2027-04-22", blockingNote: "Processor assurance & appropriateness assessments required before CDD reliance (CBUAE §5)" },
    contacts: [{ role: "Provider", name: "Shufti Pro Limited", email: "—" }],
    agreement: {
      entity: "Shufti Pro Limited", counterparty: "Mal Digital Ltd (UAE co. 25182)",
      signedFor: "Re-signed Sales Order (DocuSign)", effective: "22 April 2026", term: "36 months (commences first verification)",
      notice: "Per Terms and Conditions", commercial: "Prepaid $0.20/verification; volume 175,000 checks; setup waived",
      governingLaw: "England (Provider incorporated UK)", status: "Executed (Sales Order re-signed)", doc: "MAL x Shufti - Sales Order and Terms and Conditions (re-signed).pdf",
    },
    contractDisputes: [
      { id: "sp-d1", topic: "Support tier not specified on Sales Order", malPosition: "Confirm Basic/Priority/Premium support tier — Schedule 3 SLAs differ by tier", vendorPosition: "Schedule 3 lists tiers; Sales Order silent on selected tier", status: "Open", contractRef: "Sales Order + Schedule 3", source: DOC },
      { id: "sp-d2", topic: "99% uptime is endeavour not guarantee", malPosition: "Treat uptime as target; maintain Mal-side monitoring", vendorPosition: "Provider uses reasonable endeavours for 99% monthly uptime", status: "Acknowledged", contractRef: "Schedule 1 — Availability", source: DOC },
      { id: "sp-d3", topic: "97% accuracy is non-binding target", malPosition: "Do not rely on accuracy SLA for regulatory CDD outcomes", vendorPosition: "Stated accuracy level is target only — not guaranteed", status: "Acknowledged", contractRef: "Terms and Conditions", source: DOC },
    ],
    scores: { reporting: 76, responsiveness: 78, training: 82, audit: 80, findings: 84, timeliness: 82, quality: 80, cooperation: 80, risk: 80 },
    history: [76, 77, 79, 80, 81],
  },
  {
    id: "uqu", name: "UQU", category: "KYC & identity",
    relationship: "Mutual NDA only — no IDV services agreement in repository",
    jur: "Global", juris: ["Global"], license: "NDA stage",
    tier: "Medium", live: false, relType: "System",
    gates: { assuranceAssessed: false, appropriatenessAssessed: false, dataLocalisation: false, authControlsChecked: false, approvedBy: null, reDDDue: null, blockingNote: "Executed NDA only — no services agreement or SLA" },
    contacts: [{ role: "Counterparty", name: "Not listed in repository", email: "—" }],
    agreement: {
      entity: "UQU", counterparty: "Mal", signedFor: "Executed NDA", effective: "Per NDA", term: "Per NDA",
      notice: "—", commercial: "—", governingLaw: "Per NDA", status: "NDA only — no services contract", doc: "Mal Mutual NDA UQU.pdf",
    },
    contractDisputes: [
      { id: "uq-d1", topic: "No IDV master agreement", malPosition: "Require executed services agreement with SLA before onboarding", vendorPosition: "Mutual NDA only in repository", status: "Unresolved", contractRef: "Mal Mutual NDA UQU.pdf", source: DOC },
    ],
    scores: { reporting: 0, responsiveness: 0, training: 0, audit: 0, findings: 0, timeliness: 0, quality: 0, cooperation: 0, risk: 50 },
    history: [0, 0, 0, 0, 0],
  },
  {
    id: "verriff", name: "Veriff", category: "KYC & identity",
    relationship: "Supported countries reference only — no agreement in repository",
    jur: "Global", juris: ["Global"], license: "Not specified — supported-countries PDF only",
    tier: "Medium", live: false, relType: "System",
    gates: { assuranceAssessed: false, appropriatenessAssessed: false, dataLocalisation: false, authControlsChecked: false, approvedBy: null, reDDDue: null, blockingNote: "No contract in repository — supported-countries.pdf only" },
    contacts: [{ role: "Commercial", name: "Not listed in repository", email: "—" }],
    agreement: {
      entity: "Veriff", counterparty: "—", signedFor: "—", effective: "—", term: "—",
      notice: "—", commercial: "—", governingLaw: "—", status: "No agreement in repository", doc: "supported-countries.pdf",
    },
    contractDisputes: [
      { id: "ve-d1", topic: "No master agreement", malPosition: "Obtain and execute IDV agreement with SLA before evaluation proceeds", vendorPosition: "Only country-coverage PDF present in repository", status: "Unresolved", contractRef: "supported-countries.pdf", source: DOC },
    ],
    scores: { reporting: 0, responsiveness: 0, training: 0, audit: 0, findings: 0, timeliness: 0, quality: 0, cooperation: 0, risk: 50 },
    history: [0, 0, 0, 0, 0],
  },
  {
    id: "sardine", name: "SardineAI Corp.", category: "Risk platform",
    relationship: "Fraud platform, device intelligence, case management & AML workflows",
    jur: "United States", juris: ["United States", "Global"], license: "Risk/fraud SaaS — Customer Agreement order form",
    tier: "Critical", live: false, relType: "System",
    gates: { assuranceAssessed: false, appropriatenessAssessed: false, dataLocalisation: true, authControlsChecked: false, approvedBy: null, reDDDue: null, blockingNote: "Order form in repository — customer legal entity field blank; master agreement status unclear" },
    contacts: [{ role: "Vendor", name: "SardineAI", email: "—" }],
    agreement: {
      entity: "SardineAI Corp.", counterparty: "Legal entity not completed on order form",
      signedFor: "—", effective: "Service Start 10 December 2025", term: "3-year initial order term",
      notice: "Per Customer Agreement", commercial: "$255,000 annual minimum commitment; prepaid credits; 30-day payment terms",
      governingLaw: "Per Customer Agreement", status: "Order form (unsigned customer fields)", doc: "MAL x Sardine - Customer Agreement - 20251017.docx",
    },
    contractDisputes: [
      { id: "sa-d1", topic: "Customer legal entity blank", malPosition: "Complete Legal Entity, contacts and billing fields before execution", vendorPosition: "Order form template with unfilled customer information", status: "Open", contractRef: "Order Form — Customer Information", source: DOC },
      { id: "sa-d2", topic: "Order form vs master Customer Agreement", malPosition: "Confirm fully executed Customer Agreement governs all modules", vendorPosition: "Order form references master agreement terms", status: "Open", contractRef: "MAL x Sardine - Customer Agreement", source: DOC },
    ],
    scores: { reporting: 72, responsiveness: 74, training: 70, audit: 68, findings: 65, timeliness: 70, quality: 72, cooperation: 70, risk: 58 },
    history: [70, 71, 72, 72, 72],
  },
  {
    id: "oscilar", name: "Oscilar Inc.", category: "System integrator",
    relationship: "Transaction monitoring, real-time payment screening, alert generation — Mal TM authority (Phase 0–2)",
    jur: "United States", juris: ["United States", "Global"], license: "TM/Screening SaaS — implementation in progress",
    tier: "Critical", live: false, relType: "System",
    gates: { assuranceAssessed: false, appropriatenessAssessed: false, dataLocalisation: true, authControlsChecked: false, tmPreImplAssessment: false, approvedBy: null, reDDDue: null, blockingNote: "TM pre-implementation assessment and GATE-1–7 sign-off required before production go-live" },
    contacts: [{ role: "Vendor TM lead", name: "Oscilar Inc.", email: "—" }],
    agreement: {
      entity: "Oscilar Inc.", counterparty: "Mal Digital Ltd",
      signedFor: "—", effective: "—", term: "—",
      notice: "—", commercial: "TM + screening programme — per implementation BRD",
      governingLaw: "—", status: "Implementation — pre go-live assessment", doc: "TM_System_BRD_Mal Bank_Implementation.docx",
    },
    contractDisputes: [
      { id: "os-d1", topic: "Pre-implementation assessment incomplete", malPosition: "Complete TM questionnaire + UAT + go-live gates before production traffic", vendorPosition: "Configuration and rule deployment in progress", status: "Open", contractRef: "TM Pre-Implementation Assessment Questionnaire", source: "TM BRD 2026-06-22" },
    ],
    scores: { reporting: 60, responsiveness: 65, training: 55, audit: 58, findings: 62, timeliness: 58, quality: 64, cooperation: 66, risk: 45 },
    history: [55, 58, 60, 62, 62],
  },
  {
    id: "purpleplum", name: "PurplePlum", category: "Risk platform",
    relationship: "Digital banking stack presentation — no contract in repository",
    jur: "Global", juris: ["Global"], license: "Presentation / modules deck only",
    tier: "Medium", live: false, relType: "System",
    gates: { assuranceAssessed: false, appropriatenessAssessed: false, dataLocalisation: false, authControlsChecked: false, approvedBy: null, reDDDue: null, blockingNote: "Marketing presentation only — no executed agreement" },
    contacts: [{ role: "Commercial", name: "Not listed in repository", email: "—" }],
    agreement: {
      entity: "PurplePlum", counterparty: "—", signedFor: "—", effective: "—", term: "—",
      notice: "—", commercial: "—", governingLaw: "—", status: "Presentation only", doc: "Purpleplum_Presentation 2026.pdf",
    },
    contractDisputes: [
      { id: "pp-d1", topic: "No services agreement", malPosition: "Require executed agreement with SLA before risk-platform dependency", vendorPosition: "Presentation and module feature deck only", status: "Unresolved", contractRef: "Purpleplum_Presentation 2026.pdf", source: DOC },
    ],
    scores: { reporting: 0, responsiveness: 0, training: 0, audit: 0, findings: 0, timeliness: 0, quality: 0, cooperation: 0, risk: 50 },
    history: [0, 0, 0, 0, 0],
  },
  {
    id: "abhi", name: "Abhi", category: "Lending",
    relationship: "Earned-wage access — executed NDA and commercial proposal only",
    jur: "Pakistan", juris: ["Pakistan"], license: "EWA proposal stage",
    tier: "Medium", live: false, relType: "Outsourcing",
    gates: { s24DD: false, amlContract: false, auditRights: false, dataProtection: false, ongoingMonitoring: false, terminationRights: false, approvedBy: null, reDDDue: null, blockingNote: "NDA + proposal only — no master lending agreement" },
    contacts: [{ role: "Counterparty", name: "Not listed in repository", email: "—" }],
    agreement: {
      entity: "Abhi", counterparty: "Mal", signedFor: "NDA executed", effective: "Per NDA", term: "Per proposal (not executed)",
      notice: "—", commercial: "Abhi Proposal for Mal.pdf.pdf", governingLaw: "Per NDA / proposal", status: "NDA + proposal — no master agreement", doc: "Mutual NDA-Mal-Abhi [Execution Version].docx.pdf",
    },
    contractDisputes: [
      { id: "ab-d1", topic: "No lending master agreement", malPosition: "Execute lending/programme agreement with SLA and audit rights before launch", vendorPosition: "Commercial proposal and NDA only in repository", status: "Unresolved", contractRef: "Abhi Proposal for Mal.pdf.pdf", source: DOC },
    ],
    scores: { reporting: 0, responsiveness: 0, training: 0, audit: 0, findings: 0, timeliness: 0, quality: 0, cooperation: 0, risk: 50 },
    history: [0, 0, 0, 0, 0],
  },
];
